name: Deploy

on:
  push:
    branches:
      - main

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get -y install pandoc
          pandoc --version
      - name: Generate RSS
        run: pandoc feed.yml --template .common/template.rss >> feed.rss
      - name: Convert MD to HTML
        run: |
          find . -name "*index.md" | \
          while read i; do \
            pandoc -f markdown -t html --template=.common/template.html \
              --toc --no-highlight --mathjax "${i}" >> "${i%.md}.html"; \
          done
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./
